package com.model;

import org.codehaus.jackson.annotate.JsonManagedReference;

// Generated Nov 23, 2022 1:14:53 AM by Hibernate Tools 4.3.5.Final

/**
 * Binhluan generated by hbm2java
 */

public class Binhluan implements java.io.Serializable {

	private Integer mabinhluan;
	@JsonManagedReference
	private Nguoidung nguoidung;
	@JsonManagedReference
	private Truyen truyen;
	private String message;

	public Binhluan() {
	}

	public Binhluan(Nguoidung nguoidung, Truyen truyen, String message) {
		this.nguoidung = nguoidung;
		this.truyen = truyen;
		this.message = message;
	}

	public Integer getMabinhluan() {
		return this.mabinhluan;
	}

	public void setMabinhluan(Integer mabinhluan) {
		this.mabinhluan = mabinhluan;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	public Truyen getTruyen() {
		return this.truyen;
	}

	public void setTruyen(Truyen truyen) {
		this.truyen = truyen;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
