package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Binhluan generated by hbm2java
 */
@Entity
@Table(name = "binhluan", catalog = "apptruyen")
public class Binhluan implements java.io.Serializable {

	private Integer mabinhluan;
	private Nguoidung nguoidung;
	private Truyen truyen;
	private String message;

	public Binhluan() {
	}

	public Binhluan(Nguoidung nguoidung, Truyen truyen, String message) {
		this.nguoidung = nguoidung;
		this.truyen = truyen;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mabinhluan", unique = true, nullable = false)
	public Integer getMabinhluan() {
		return this.mabinhluan;
	}

	public void setMabinhluan(Integer mabinhluan) {
		this.mabinhluan = mabinhluan;
	}

	@ManyToOne
	@JsonBackReference
	@JoinColumn(name = "manguoidung", nullable = false)
	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	@ManyToOne
	@JsonBackReference
	@JoinColumn(name = "matruyen", nullable = false)
	public Truyen getTruyen() {
		return this.truyen;
	}

	public void setTruyen(Truyen truyen) {
		this.truyen = truyen;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
