package com.model;
// Generated Nov 29, 2022 12:51:20 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Binhluan generated by hbm2java
 */
public class Binhluan implements java.io.Serializable {

	private Integer mabinhluan;
	@JsonBackReference
	private Nguoidung nguoidung;
	@JsonBackReference
	private Truyen truyen;
	private String message;
	private Date ngaydang;

	public Binhluan() {
	}

	public Binhluan(Nguoidung nguoidung, Truyen truyen, String message, Date ngaydang) {
		this.nguoidung = nguoidung;
		this.truyen = truyen;
		this.message = message;
		this.ngaydang = ngaydang;
	}

	public Integer getMabinhluan() {
		return this.mabinhluan;
	}

	public void setMabinhluan(Integer mabinhluan) {
		this.mabinhluan = mabinhluan;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	public Truyen getTruyen() {
		return this.truyen;
	}

	public void setTruyen(Truyen truyen) {
		this.truyen = truyen;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getNgaydang() {
		return this.ngaydang;
	}

	public void setNgaydang(Date ngaydang) {
		this.ngaydang = ngaydang;
	}

}
