package com.model;
// Generated Nov 29, 2022 12:51:20 AM by Hibernate Tools 4.3.5.Final

/**
 * Chuong generated by hbm2java
 */
public class Chuong implements java.io.Serializable {

	private Integer machuong;
	private Tap tap;
	private String tenchuong;
	private String noidungtruyen;

	public Chuong() {
	}

	public Chuong(Tap tap, String tenchuong, String noidungtruyen) {
		this.tap = tap;
		this.tenchuong = tenchuong;
		this.noidungtruyen = noidungtruyen;
	}

	public Integer getMachuong() {
		return this.machuong;
	}

	public void setMachuong(Integer machuong) {
		this.machuong = machuong;
	}

	public Tap getTap() {
		return this.tap;
	}

	public void setTap(Tap tap) {
		this.tap = tap;
	}

	public String getTenchuong() {
		return this.tenchuong;
	}

	public void setTenchuong(String tenchuong) {
		this.tenchuong = tenchuong;
	}

	public String getNoidungtruyen() {
		return this.noidungtruyen;
	}

	public void setNoidungtruyen(String noidungtruyen) {
		this.noidungtruyen = noidungtruyen;
	}

}
