package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Chuong generated by hbm2java
 */
@Entity
@Table(name = "chuong", catalog = "apptruyen")
public class Chuong implements java.io.Serializable {

	private Integer machuong;
	private Tap tap;
	private String tenchuong;
	private String noidungtruyen;

	public Chuong() {
	}

	public Chuong(Tap tap, String tenchuong, String noidungtruyen) {
		this.tap = tap;
		this.tenchuong = tenchuong;
		this.noidungtruyen = noidungtruyen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "machuong", unique = true, nullable = false)
	public Integer getMachuong() {
		return this.machuong;
	}

	public void setMachuong(Integer machuong) {
		this.machuong = machuong;
	}

	@ManyToOne
	@JsonBackReference
	@JoinColumn(name = "matap", nullable = false)
	public Tap getTap() {
		return this.tap;
	}

	public void setTap(Tap tap) {
		this.tap = tap;
	}

	@Column(name = "tenchuong", nullable = false, length = 100)
	public String getTenchuong() {
		return this.tenchuong;
	}

	public void setTenchuong(String tenchuong) {
		this.tenchuong = tenchuong;
	}

	@Column(name = "noidungtruyen", nullable = false, length = 65535)
	public String getNoidungtruyen() {
		return this.noidungtruyen;
	}

	public void setNoidungtruyen(String noidungtruyen) {
		this.noidungtruyen = noidungtruyen;
	}

	@Override
	public String toString() {
		return "Chuong [machuong=" + machuong + ", tap=" + tap + ", tenchuong=" + tenchuong + ", noidungtruyen="
				+ noidungtruyen + "]";
	}

}
