package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Nguoidung generated by hbm2java
 */
@Entity
@Table(name = "nguoidung", catalog = "apptruyen", uniqueConstraints = @UniqueConstraint(columnNames = "tentaikhoan"))
public class Nguoidung implements java.io.Serializable {

	private Integer manguoidung;
	private String tennguoidung;
	private String hinhdaidien;
	private String matkhau;
	private String tentaikhoan;
	private Set<Binhluan> binhluans = new HashSet<Binhluan>(0);
	private Set<TruyenNd> truyenNds = new HashSet<TruyenNd>(0);

	public Nguoidung() {
	}

	public Nguoidung(String tennguoidung, String matkhau, String tentaikhoan) {
		this.tennguoidung = tennguoidung;
		this.matkhau = matkhau;
		this.tentaikhoan = tentaikhoan;
	}

	public Nguoidung(String tennguoidung, String hinhdaidien, String matkhau, String tentaikhoan,
			Set<Binhluan> binhluans, Set<TruyenNd> truyenNds) {
		this.tennguoidung = tennguoidung;
		this.hinhdaidien = hinhdaidien;
		this.matkhau = matkhau;
		this.tentaikhoan = tentaikhoan;
		this.binhluans = binhluans;
		this.truyenNds = truyenNds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "manguoidung", unique = true, nullable = false)
	public Integer getManguoidung() {
		return this.manguoidung;
	}

	public void setManguoidung(Integer manguoidung) {
		this.manguoidung = manguoidung;
	}

	@Column(name = "tennguoidung", nullable = false, length = 50)
	public String getTennguoidung() {
		return this.tennguoidung;
	}

	public void setTennguoidung(String tennguoidung) {
		this.tennguoidung = tennguoidung;
	}

	@Column(name = "hinhdaidien", length = 65535)
	public String getHinhdaidien() {
		return this.hinhdaidien;
	}

	public void setHinhdaidien(String hinhdaidien) {
		this.hinhdaidien = hinhdaidien;
	}

	@Column(name = "matkhau", nullable = false, length = 50)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "tentaikhoan", unique = true, nullable = false, length = 50)
	public String getTentaikhoan() {
		return this.tentaikhoan;
	}

	public void setTentaikhoan(String tentaikhoan) {
		this.tentaikhoan = tentaikhoan;
	}

	@OneToMany( mappedBy = "nguoidung")
	@JsonManagedReference
	public Set<Binhluan> getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set<Binhluan> binhluans) {
		this.binhluans = binhluans;
	}

	@OneToMany( mappedBy = "nguoidung")
	@JsonManagedReference
	public Set<TruyenNd> getTruyenNds() {
		return this.truyenNds;
	}

	public void setTruyenNds(Set<TruyenNd> truyenNds) {
		this.truyenNds = truyenNds;
	}

}
