package com.model;
// Generated Nov 29, 2022 12:51:20 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung implements java.io.Serializable {

	private Integer manguoidung;
	private String tennguoidung;
	private String hinhdaidien;
	private String matkhau;
	private String tentaikhoan;
	private Set<Binhluan> binhluans = new HashSet<Binhluan>(0);
	private Set<TruyenNd> truyenNds = new HashSet<TruyenNd>(0);

	public Nguoidung() {
	}

	public Nguoidung(String tennguoidung, String matkhau, String tentaikhoan) {
		this.tennguoidung = tennguoidung;
		this.matkhau = matkhau;
		this.tentaikhoan = tentaikhoan;
	}

	public Nguoidung(String tennguoidung, String hinhdaidien, String matkhau, String tentaikhoan,
			Set<Binhluan> binhluans, Set<TruyenNd> truyenNds) {
		this.tennguoidung = tennguoidung;
		this.hinhdaidien = hinhdaidien;
		this.matkhau = matkhau;
		this.tentaikhoan = tentaikhoan;
		this.binhluans = binhluans;
		this.truyenNds = truyenNds;
	}

	public Integer getManguoidung() {
		return this.manguoidung;
	}

	public void setManguoidung(Integer manguoidung) {
		this.manguoidung = manguoidung;
	}

	public String getTennguoidung() {
		return this.tennguoidung;
	}

	public void setTennguoidung(String tennguoidung) {
		this.tennguoidung = tennguoidung;
	}

	public String getHinhdaidien() {
		return this.hinhdaidien;
	}

	public void setHinhdaidien(String hinhdaidien) {
		this.hinhdaidien = hinhdaidien;
	}

	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	public String getTentaikhoan() {
		return this.tentaikhoan;
	}

	public void setTentaikhoan(String tentaikhoan) {
		this.tentaikhoan = tentaikhoan;
	}

	public Set<Binhluan> getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set<Binhluan> binhluans) {
		this.binhluans = binhluans;
	}

	public Set<TruyenNd> getTruyenNds() {
		return this.truyenNds;
	}

	public void setTruyenNds(Set<TruyenNd> truyenNds) {
		this.truyenNds = truyenNds;
	}

}
