package com.model;
// Generated Nov 29, 2022 12:51:20 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Tacgia generated by hbm2java
 */
public class Tacgia implements java.io.Serializable {

	private Integer matacgia;
	private String tentacgia;
	@JsonBackReference
	private Set<Truyen> truyens = new HashSet<Truyen>(0);

	public Tacgia() {
	}

	public Tacgia(String tentacgia) {
		this.tentacgia = tentacgia;
	}

	public Tacgia(String tentacgia, Set<Truyen> truyens) {
		this.tentacgia = tentacgia;
		this.truyens = truyens;
	}

	public Integer getMatacgia() {
		return this.matacgia;
	}

	public void setMatacgia(Integer matacgia) {
		this.matacgia = matacgia;
	}

	public String getTentacgia() {
		return this.tentacgia;
	}

	public void setTentacgia(String tentacgia) {
		this.tentacgia = tentacgia;
	}

	public Set<Truyen> getTruyens() {
		return this.truyens;
	}

	public void setTruyens(Set<Truyen> truyens) {
		this.truyens = truyens;
	}

}
