package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Tacgia generated by hbm2java
 */
@Entity
@Table(name = "tacgia", catalog = "apptruyen")
public class Tacgia implements java.io.Serializable {

	private Integer matacgia;
	private String tentacgia;
	private Set<Truyen> truyens = new HashSet<Truyen>(0);

	public Tacgia() {
	}

	public Tacgia(String tentacgia) {
		this.tentacgia = tentacgia;
	}

	public Tacgia(String tentacgia, Set<Truyen> truyens) {
		this.tentacgia = tentacgia;
		this.truyens = truyens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "matacgia", unique = true, nullable = false)
	public Integer getMatacgia() {
		return this.matacgia;
	}

	public void setMatacgia(Integer matacgia) {
		this.matacgia = matacgia;
	}

	@Column(name = "tentacgia", nullable = false, length = 100)
	public String getTentacgia() {
		return this.tentacgia;
	}

	public void setTentacgia(String tentacgia) {
		this.tentacgia = tentacgia;
	}

	@OneToMany( mappedBy = "tacgia")
	@JsonManagedReference
	public Set<Truyen> getTruyens() {
		return this.truyens;
	}

	public void setTruyens(Set<Truyen> truyens) {
		this.truyens = truyens;
	}

}
