package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Tap generated by hbm2java
 */
@Entity
@Table(name = "tap", catalog = "apptruyen")
public class Tap implements java.io.Serializable {

	private Integer matap;
	private Truyen truyen;
	private String tentap;
	private Set<Chuong> chuongs = new HashSet<Chuong>(0);

	public Tap() {
	}

	public Tap(Truyen truyen, String tentap) {
		this.truyen = truyen;
		this.tentap = tentap;
	}

	public Tap(Truyen truyen, String tentap, Set<Chuong> chuongs) {
		this.truyen = truyen;
		this.tentap = tentap;
		this.chuongs = chuongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "matap", unique = true, nullable = false)
	public Integer getMatap() {
		return this.matap;
	}

	public void setMatap(Integer matap) {
		this.matap = matap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matruyen", nullable = false)
	public Truyen getTruyen() {
		return this.truyen;
	}

	public void setTruyen(Truyen truyen) {
		this.truyen = truyen;
	}

	@Column(name = "tentap", nullable = false, length = 100)
	public String getTentap() {
		return this.tentap;
	}

	public void setTentap(String tentap) {
		this.tentap = tentap;
	}

	@OneToMany( mappedBy = "tap")
	@JsonManagedReference
	public Set<Chuong> getChuongs() {
		return this.chuongs;
	}

	public void setChuongs(Set<Chuong> chuongs) {
		this.chuongs = chuongs;
	}

}
