package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Theloai generated by hbm2java
 */
@Entity
@Table(name = "theloai", catalog = "apptruyen")
public class Theloai implements java.io.Serializable {

	private Integer matheloai;
	private String tentheloai;
	private Set<Truyen> truyens = new HashSet<Truyen>(0);

	public Theloai() {
	}

	public Theloai(String tentheloai) {
		this.tentheloai = tentheloai;
	}

	public Theloai(String tentheloai, Set<Truyen> truyens) {
		this.tentheloai = tentheloai;
		this.truyens = truyens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "matheloai", unique = true, nullable = false)
	public Integer getMatheloai() {
		return this.matheloai;
	}

	public void setMatheloai(Integer matheloai) {
		this.matheloai = matheloai;
	}

	@Column(name = "tentheloai", nullable = false, length = 50)
	public String getTentheloai() {
		return this.tentheloai;
	}

	public void setTentheloai(String tentheloai) {
		this.tentheloai = tentheloai;
	}

	@ManyToMany( mappedBy = "theloais")
	@JsonManagedReference
	public Set<Truyen> getTruyens() {
		return this.truyens;
	}

	public void setTruyens(Set<Truyen> truyens) {
		this.truyens = truyens;
	}

}
