package com.model;
// Generated Nov 23, 2022 1:14:53 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Theloai generated by hbm2java
 */
public class Theloai implements java.io.Serializable {

	private Integer matheloai;
	private String tentheloai;
	@JsonBackReference
	private Set<Truyen> truyens = new HashSet<Truyen>(0);

	public Theloai() {
	}

	public Theloai(String tentheloai) {
		this.tentheloai = tentheloai;
	}

	public Theloai(String tentheloai, Set<Truyen> truyens) {
		this.tentheloai = tentheloai;
		this.truyens = truyens;
	}

	public Integer getMatheloai() {
		return this.matheloai;
	}

	public void setMatheloai(Integer matheloai) {
		this.matheloai = matheloai;
	}

	public String getTentheloai() {
		return this.tentheloai;
	}

	public void setTentheloai(String tentheloai) {
		this.tentheloai = tentheloai;
	}

	public Set<Truyen> getTruyens() {
		return this.truyens;
	}

	public void setTruyens(Set<Truyen> truyens) {
		this.truyens = truyens;
	}

}
