package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * TruyenNd generated by hbm2java
 */
@Entity
@Table(name = "truyen_nd", catalog = "apptruyen")
public class TruyenNd implements java.io.Serializable {

	private TruyenNdId id;
	private Nguoidung nguoidung;
	private Truyen truyen;
	private Date ngayxem;

	public TruyenNd() {
	}

	public TruyenNd(TruyenNdId id, Nguoidung nguoidung, Truyen truyen, Date ngayxem) {
		this.id = id;
		this.nguoidung = nguoidung;
		this.truyen = truyen;
		this.ngayxem = ngayxem;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "matruyen", column = @Column(name = "matruyen", nullable = false)),
			@AttributeOverride(name = "mand", column = @Column(name = "mand", nullable = false)) })
	public TruyenNdId getId() {
		return this.id;
	}

	public void setId(TruyenNdId id) {
		this.id = id;
	}

	@ManyToOne
	@JsonBackReference
	@JoinColumn(name = "mand", nullable = false, insertable = false, updatable = false)
	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	@ManyToOne
	@JsonBackReference
	@JoinColumn(name = "matruyen", nullable = false, insertable = false, updatable = false)
	public Truyen getTruyen() {
		return this.truyen;
	}

	public void setTruyen(Truyen truyen) {
		this.truyen = truyen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngayxem", nullable = false, length = 10)
	public Date getNgayxem() {
		return this.ngayxem;
	}

	public void setNgayxem(Date ngayxem) {
		this.ngayxem = ngayxem;
	}

}
