package com.model;
// Generated Nov 22, 2022 8:50:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Truyen generated by hbm2java
 */
@Entity
@Table(name = "truyen", catalog = "apptruyen")
public class Truyen implements java.io.Serializable {

	private Integer matruyen;
	private Tacgia tacgia;
	private String tentruyen;
	private String mota;
	private Date ngaydang;
	private String hinh;
	private Set<TruyenNd> truyenNds = new HashSet<TruyenNd>(0);
	private Set<Binhluan> binhluans = new HashSet<Binhluan>(0);
	private Set<Tap> taps = new HashSet<Tap>(0);
	private Set<Theloai> theloais = new HashSet<Theloai>(0);

	public Truyen() {
	}

	public Truyen(Tacgia tacgia, String tentruyen, String mota, Date ngaydang) {
		this.tacgia = tacgia;
		this.tentruyen = tentruyen;
		this.mota = mota;
		this.ngaydang = ngaydang;
	}

	public Truyen(Tacgia tacgia, String tentruyen, String mota, Date ngaydang, String hinh, Set<TruyenNd> truyenNds,
			Set<Binhluan> binhluans, Set<Tap> taps, Set<Theloai> theloais) {
		this.tacgia = tacgia;
		this.tentruyen = tentruyen;
		this.mota = mota;
		this.ngaydang = ngaydang;
		this.hinh = hinh;
		this.truyenNds = truyenNds;
		this.binhluans = binhluans;
		this.taps = taps;
		this.theloais = theloais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "matruyen", unique = true, nullable = false)
	public Integer getMatruyen() {
		return this.matruyen;
	}

	public void setMatruyen(Integer matruyen) {
		this.matruyen = matruyen;
	}

	@ManyToOne
	@JsonBackReference
	@JoinColumn(name = "matacgia", nullable = false)
	public Tacgia getTacgia() {
		return this.tacgia;
	}

	public void setTacgia(Tacgia tacgia) {
		this.tacgia = tacgia;
	}

	@Column(name = "tentruyen", nullable = false, length = 100)
	public String getTentruyen() {
		return this.tentruyen;
	}

	public void setTentruyen(String tentruyen) {
		this.tentruyen = tentruyen;
	}

	@Column(name = "mota", nullable = false, length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaydang", nullable = false, length = 10)
	public Date getNgaydang() {
		return this.ngaydang;
	}

	public void setNgaydang(Date ngaydang) {
		this.ngaydang = ngaydang;
	}

	@Column(name = "hinh", length = 65535)
	public String getHinh() {
		return this.hinh;
	}

	public void setHinh(String hinh) {
		this.hinh = hinh;
	}

	@OneToMany( mappedBy = "truyen")
	@JsonManagedReference
	public Set<TruyenNd> getTruyenNds() {
		return this.truyenNds;
	}

	public void setTruyenNds(Set<TruyenNd> truyenNds) {
		this.truyenNds = truyenNds;
	}

	@OneToMany( mappedBy = "truyen")
	@JsonManagedReference
	public Set<Binhluan> getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set<Binhluan> binhluans) {
		this.binhluans = binhluans;
	}

	@OneToMany( mappedBy = "truyen")
	@JsonManagedReference
	public Set<Tap> getTaps() {
		return this.taps;
	}

	public void setTaps(Set<Tap> taps) {
		this.taps = taps;
	}

	@ManyToMany
	@JsonManagedReference
	@JoinTable(name = "truyen_theloai", catalog = "apptruyen", joinColumns = {
			@JoinColumn(name = "matruyen", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "matheloai", nullable = false, updatable = false) })
	public Set<Theloai> getTheloais() {
		return this.theloais;
	}

	public void setTheloais(Set<Theloai> theloais) {
		this.theloais = theloais;
	}

}
