package com.model;
// Generated Nov 29, 2022 12:51:20 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Truyen generated by hbm2java
 */
public class Truyen implements java.io.Serializable {

	private Integer matruyen;
	@JsonManagedReference
	private Tacgia tacgia;
	private String tentruyen;
	private String mota;
	private Date ngaydang;
	private String hinh;
	@JsonBackReference
	private Set<TruyenNd> truyenNds = new HashSet<TruyenNd>(0);
	@JsonBackReference
	private Set<Binhluan> binhluans = new HashSet<Binhluan>(0);
	@JsonBackReference
	private Set<Tap> taps = new HashSet<Tap>(0);
	@JsonBackReference
	private Set<Theloai> theloais = new HashSet<Theloai>(0);

	public Truyen() {
	}

	public Truyen(Tacgia tacgia, String tentruyen, String mota, Date ngaydang) {
		this.tacgia = tacgia;
		this.tentruyen = tentruyen;
		this.mota = mota;
		this.ngaydang = ngaydang;
	}

	public Truyen(Tacgia tacgia, String tentruyen, String mota, Date ngaydang, String hinh, Set<TruyenNd> truyenNds,
			Set<Binhluan> binhluans, Set<Tap> taps, Set<Theloai> theloais) {
		this.tacgia = tacgia;
		this.tentruyen = tentruyen;
		this.mota = mota;
		this.ngaydang = ngaydang;
		this.hinh = hinh;
		this.truyenNds = truyenNds;
		this.binhluans = binhluans;
		this.taps = taps;
		this.theloais = theloais;
	}

	public Integer getMatruyen() {
		return this.matruyen;
	}

	public void setMatruyen(Integer matruyen) {
		this.matruyen = matruyen;
	}

	public Tacgia getTacgia() {
		return this.tacgia;
	}

	public void setTacgia(Tacgia tacgia) {
		this.tacgia = tacgia;
	}

	public String getTentruyen() {
		return this.tentruyen;
	}

	public void setTentruyen(String tentruyen) {
		this.tentruyen = tentruyen;
	}

	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	public Date getNgaydang() {
		return this.ngaydang;
	}

	public void setNgaydang(Date ngaydang) {
		this.ngaydang = ngaydang;
	}

	public String getHinh() {
		return this.hinh;
	}

	public void setHinh(String hinh) {
		this.hinh = hinh;
	}

	public Set<TruyenNd> getTruyenNds() {
		return this.truyenNds;
	}

	public void setTruyenNds(Set<TruyenNd> truyenNds) {
		this.truyenNds = truyenNds;
	}

	public Set<Binhluan> getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set<Binhluan> binhluans) {
		this.binhluans = binhluans;
	}

	public Set<Tap> getTaps() {
		return this.taps;
	}

	public void setTaps(Set<Tap> taps) {
		this.taps = taps;
	}

	public Set<Theloai> getTheloais() {
		return this.theloais;
	}

	public void setTheloais(Set<Theloai> theloais) {
		this.theloais = theloais;
	}

}
