package com.model;
// Generated Nov 23, 2022 1:14:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * TruyenNd generated by hbm2java
 */
public class TruyenNd implements java.io.Serializable {

	private TruyenNdId id;
	@JsonManagedReference
	private Nguoidung nguoidung;
	@JsonManagedReference
	private Truyen truyen;
	private Date ngayxem;

	public TruyenNd() {
	}

	public TruyenNd(TruyenNdId id, Nguoidung nguoidung, Truyen truyen, Date ngayxem) {
		this.id = id;
		this.nguoidung = nguoidung;
		this.truyen = truyen;
		this.ngayxem = ngayxem;
	}

	public TruyenNdId getId() {
		return this.id;
	}

	public void setId(TruyenNdId id) {
		this.id = id;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	public Truyen getTruyen() {
		return this.truyen;
	}

	public void setTruyen(Truyen truyen) {
		this.truyen = truyen;
	}

	public Date getNgayxem() {
		return this.ngayxem;
	}

	public void setNgayxem(Date ngayxem) {
		this.ngayxem = ngayxem;
	}

}
